### ISSUE TITLE
Update Button to use the new core component pressable

### ISSUE THREAD

**Issue by solarsoft0** [jsartisan/react-native-magnus#10]
Pressable is a Core Component wrapper that can detect various stages of press interactions on any of it's defined, children.
will be glad to send in PR for this, let me know what you think :)

**Comment by jsartisan** [comment]
@solarsoft0 I would love to accept PRs :D

**Comment by solarsoft0** [comment]
> @solarsoft0 I would love to accept PRs :D 

Ok sure, will do just that :)

**Comment by solarsoft0** [comment]
@jsartisan I have worked on this like discussed, please take a look https://github.com/jsartisan/react-native-magnus/pull/13

**Comment by jsartisan** [comment]
@solarsoft0 Merged your pull request :D Thanks a lot for it. Are you on discord or twitter? I want to give you a shoutout?

Can you verify your pull request in 1.0.41 version?

**Comment by solarsoft0** [comment]
I'm on twitter @solarsoft0, thanks a lot, will verify the update
