### ISSUE TITLE
How do I change the font

### ISSUE THREAD

**Issue by chamatt** [jsartisan/react-native-magnus#11]
Hey, just wanted to start of thanking you for this awesome library!

The problem I'm facing right now is that I can't find how to change the default font. Is there a recommended way of doing that?

And also, is there a way to specify another font-family as the "bold"? For example, when using expo-google-fonts, I import RobotoSlab_400 and use that as the "normal" weight, and RobotoSlab_700 as the "bold" weight.

Also, as a side note: Is there any way to import the default theme, so I can use the colors somewhere outside the library, like in the StyledComponents Theme provider? Maybe a useTheme hook?

**Comment by jsartisan** [comment]
@chamatt Thanks for the kind words.

> The problem I'm facing right now is that I can't find how to change the default font. Is there a recommended way of doing that?
- You will need to import your fonts according to certain format react native requires. You can follow this guide for that - https://medium.com/@mehrankhandev/ultimate-guide-to-use-custom-fonts-in-react-native-77fcdf859cf4

After that, You can simply use fontFamily props to specify the font like *fontFamily: SFUIDisplay-Bold* on <Text> component.
If you are looking for a better API or have any suggestion, I would love to implement it. :D
I can also write a blog for using custom fonts with magnus that helps.

> Also, as a side note: Is there any way to import the default theme, so I can use the colors somewhere outside the library, like in the StyledComponents Theme provider? Maybe a useTheme hook? 
- I am actually exporting withTheme hook. Sorry, I didn't add the usage of it in docs. Will do so. 😅

**Comment by chamatt** [comment]
Thank you for the response! I will try that asap!

> We are actually exporting withTheme hook. Sorry, I didn't add the usage of it in docs. Will do so. sweat_smile
hehe
