### ISSUE TITLE
[Bug] after installing magnus-ui in expo app getting error "No Space between hexadecimal literal and identifier

### ISSUE THREAD

**Issue by iamdonprince** [jsartisan/react-native-magnus#113]
## Description

[What happened]

### Steps to reproduce the behaviour:

Add steps to reproduce this behaviour, include console / network logs & screenshots

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]

**Comment by ayrtonlacerda** [comment]
Same issue

**Comment by iamdonprince** [comment]
I changed the version of the color package to `color@3.2.1`
and it worked
