### ISSUE TITLE
Wrong Types using TypeScript

### ISSUE THREAD

**Issue by juanlatorre** [jsartisan/react-native-magnus#14]
Hey, I found an error in a lot of types as "shadow" that requires a number, but on docs it require a String and minW also asks for a number, when it should be asking for a string.

It works but I have to put // @ts-expect-error on every prop with wrong type declaration.

![code1](https://user-images.githubusercontent.com/4494526/88951503-14750f80-d264-11ea-87cc-dfe29c0832c4.png)

**Comment by jsartisan** [comment]
@juanlatorre Really sorry for this. I'll try to fix it this weekend.

**Comment by jsartisan** [comment]
@juanlatorre released a new version ( 1.0.41 ) Can you verify if it is fixed?

**Comment by juanlatorre** [comment]
> @juanlatorre released a new version ( 1.0.41 ) Can you verify if it is fixed?

It is completely fixed, thank you very much !
