### ISSUE TITLE
Issues on Documentation page

### ISSUE THREAD

**Issue by wethil** [jsartisan/react-native-magnus#15]
[The documents page for Divs](https://magnus-ui.com/docs/div/) acting weird at the moment
<img width="1645" alt="Screen Shot 2020-08-01 at 23 00 19" src="https://user-images.githubusercontent.com/6503960/89109550-d554e300-d44a-11ea-9fb3-80e1d650e2a6.png">

Can you check it?

**Comment by jsartisan** [comment]
@wethil Fixed. Thanks a lot for pointing it out. Had an extra `</div>` 😅

**Comment by jsartisan** [comment]
@wethil Can you verify it on your end and close the issue?
