### ISSUE TITLE
got Button related error when bump update from 1.0.40 to 1.0.41

### ISSUE THREAD

**Issue by yareyaredesuyo** [jsartisan/react-native-magnus#17]
I got following error when bump updated library.

![スクリーンショット 2020-08-06 21 13 22](https://user-images.githubusercontent.com/31843888/89530612-c47ce680-d829-11ea-97e1-f1c3fc0075e7.png)

Tried this example source code. 

https://snack.expo.io/@pawankumar2901/dribble-login-page

Maybe related to this change? https://github.com/jsartisan/react-native-magnus/commit/1df30b716dab3eb3cbfb47406a512d882c360e0f

**Comment by jsartisan** [comment]
Really sorry about this. I will try to get this fixed today.

**Comment by jsartisan** [comment]
@yareyaredesuyo Can you follow the answer from here?

https://stackoverflow.com/questions/60880105/cocoapods-could-not-find-compatible-versions-for-pod-reactcommon-jscallinvoker. This step will be required for our version 1.0.41 as it uses react native 0.63

**Comment by yareyaredesuyo** [comment]
@jsartisan 

Sorry, I'm tested it in expo38.

**Comment by GaspardC** [comment]
@yamatsum did you find a solution ? I'm also using expo38

**Comment by jsartisan** [comment]
Actually we updated our button component from Touchable to Pressable which came just now in new version of react-native. I can revert it if it is creating too much issue for everyone :/

**Comment by GaspardC** [comment]
@jsartisan thanks it's fine for me with the 1.0.40, it should be fixed when expo 39 rolls out

**Comment by jsartisan** [comment]
@GaspardC You should be able to use the latest version of magnus as expo rolled out support for pressable component.

**Comment by GaspardC** [comment]
@jsartisan yes it is and working great 🥳
