### ISSUE TITLE
Alius Box as Div

### ISSUE THREAD

**Issue by yareyaredesuyo** [jsartisan/react-native-magnus#18]
For standard styled system, there is alot of case use Box as main responsible component.

So, I think it maybe a good idea to alias Box as Div which following styled system convention.

**Comment by jsartisan** [comment]
@yareyaredesuyo Actually initially I was also planning to use Box, but since most react native developers come from the web background, they are familiar with the word 'div'. If you really want a Box component, I can export an alias of Div as Box. works?

**Comment by yareyaredesuyo** [comment]
@jsartisan 

Yeah, those people who are familiar with `styled system` maybe like using Box, so aliasing is hit the target.

**Comment by jsartisan** [comment]
@yareyaredesuyo This is done in version 1.0.42. Thanks for the suggestion :D
