### ISSUE TITLE
Support for direction aware style props

### ISSUE THREAD

**Issue by tomslutsky** [jsartisan/react-native-magnus#2]
I am missing the option to use direction aware style props such as `marginStart` or `borderEndWidth`.
I would be happy to PR it but not sure how your dev workflow is going.

**Comment by koolamusic** [comment]
@jsartisan are there any areas you need assistance with. Maybe documentation, enhancements, If there is a project/vision board, I think some of us can help.

Keep up with the good work.

**Comment by jsartisan** [comment]
@tomslutsky Added marginStart and borderEndWith ( version 1.0.39 ) I will be updating docs as well in a few days.

**Comment by jsartisan** [comment]
@koolamusic Thanks :) I would love to get help on this project. 👍

**Comment by jsartisan** [comment]
@koolamusic Let's chat on discord channel if possible.
