### ISSUE TITLE
Select Footer Button always Open

### ISSUE THREAD

**Issue by horlaarsco** [jsartisan/react-native-magnus#20]
Setting multiple to false still renders the footer button, I had to fix this way.. Can i go on and send a PR?

And also i cant seem to set an height on the select container.. 

![image](https://user-images.githubusercontent.com/10059733/91625279-e9cec180-e99d-11ea-83f9-859ac0151c99.png)

Also render title too react node doesnt work with it, gives error of object is not valid as a react child.. 

Worked after This

![image](https://user-images.githubusercontent.com/10059733/91625331-6792cd00-e99e-11ea-8db1-9df1393f441a.png)

Ill send the Pr soon..

**Comment by jsartisan** [comment]
@horlaarsco Are you working on this? I can fix this real quick if you want?

**Comment by horlaarsco** [comment]
> @horlaarsco Are you working on this? I can fix this real quick if you want?

Sorry was a bit busy, Here is the link to the PR
https://github.com/jsartisan/react-native-magnus/pull/22

Thanks for magnus :)

**Comment by jsartisan** [comment]
@horlaarsco Thanks for the pull request. Just released the version 1.0.42 with your pull request merged :) 

Thanks a lot again.
