### ISSUE TITLE
react-native-web-modal

### ISSUE THREAD

**Issue by globophobe** [jsartisan/react-native-magnus#23]
Great library! It would be nice to support something like react-native-web-modal for use with react-native-web.

**Comment by jsartisan** [comment]
Thanks a lot for the kind words :) I will definitely look into it.

**Comment by jsartisan** [comment]
@globophobe Thinking of implementing this - https://www.npmjs.com/package/modal-react-native-web

**Comment by jsartisan** [comment]
@globophobe I just saw that react-native-modal works on the web with the latest version. I will be updating the example app for reference :D

**Comment by globophobe** [comment]
Awesome! Thanks again for the great library

**Comment by jsartisan** [comment]
Closing the issue. You can the example app for reference :)
