### ISSUE TITLE
Can click on FAB hidden options.

### ISSUE THREAD

**Issue by juanlatorre** [jsartisan/react-native-magnus#34]
Hi! Found a nasty bug today, it seems that hidden options inside a FAB can be pressed at any time.

![GIF](https://user-images.githubusercontent.com/4494526/97902762-c9641000-1d1c-11eb-9e5e-1c48c31dde7d.gif)

**Comment by jsartisan** [comment]
@juanlatorre This is fixed in the new version. Can you close after verifying at your end?

**Comment by juanlatorre** [comment]
Verified, it's fixed, sorry for being late
