### ISSUE TITLE
Div BorderRightColor doesn't work

### ISSUE THREAD

**Issue by erickriva** [jsartisan/react-native-magnus#38]
I'm using "borderRight" properties on **Div** component and **borderRightColor** don't work. But borderLeftColor do.

This is my code:
![a](https://user-images.githubusercontent.com/2746558/101699374-50727980-3a7b-11eb-9524-154618c729c9.jpg)

and the result:
![test](https://user-images.githubusercontent.com/2746558/101698992-ba3e5380-3a7a-11eb-9f22-aa44c4d519ce.png)

**Comment by jsartisan** [comment]
Thanks for reporting the issue. I have merged your PR but let's close the issue when we will be releasing the new version.

**Comment by jsartisan** [comment]
@erickriva The PR is merged in v1.0.56

**Comment by erickriva** [comment]
Great! I've tried it and was fixed!
