### ISSUE TITLE
React Native Web support

### ISSUE THREAD

**Issue by sweeetland** [jsartisan/react-native-magnus#4]
Awesome library... does this work with [react-native-web](https://github.com/necolas/react-native-web)?

**Comment by jsartisan** [comment]
Thanks for the kind words :) 

Most things should work with react-native-web. I checked on Expo. It was working pretty well on the browser.

**Comment by jsartisan** [comment]
@sweeetland I have updated the example that works on the web too :D
Closing the issue.
