### ISSUE TITLE
TextInput textAlign prop doesn't exists on Input

### ISSUE THREAD

**Issue by erickriva** [jsartisan/react-native-magnus#44]
Why TextInput textAlign prop does not exists on Input?
`textAlign="center"` works well but it is not included in Input types.

![image](https://user-images.githubusercontent.com/2746558/102017673-9b84d900-3d68-11eb-9e51-959f4c0591d8.png)

**Comment by erickriva** [comment]
I have discovered that this prop doesn't exists on React Native types, but exists on React Native docs.
I've tried, but i don't know how to pull request on DefinitelyTyped. It's such a big project to download it fully.

**Comment by jsartisan** [comment]
Let me check if text alignment is supported in the inputs.

**Comment by jsartisan** [comment]
Seems to be working :D I have added the support in the local rep on my machine. Let's close the issue once we release new version.

**Comment by erickriva** [comment]
Follow 'textAlign' PR status here:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50146

**Comment by erickriva** [comment]
Resolved on v1.0.57
