### ISSUE TITLE
[Suggestion] Use Github Actions to publish Example App to Expo

### ISSUE THREAD

**Issue by erickriva** [jsartisan/react-native-magnus#46]
Have you heard about this extension for Github?
You can use it and publish Example App to Expo, then put the link on README for get easy to people to give a look on what this project can do.

https://github.com/expo/expo-github-action#publish-on-any-push-to-master

**Comment by jsartisan** [comment]
Great suggestion. I'll try to add it today.

**Comment by jsartisan** [comment]
@erickriva Done. 👍 
https://expo.io/@pawankumar2901/projects/react-native-magnus-example
