### ISSUE TITLE
[Bug] global.__expo.Icon Deprecated Warning Expo SDK 40

### ISSUE THREAD

**Issue by rifaldhiaw** [jsartisan/react-native-magnus#51]
## Description
There is a warning about the `global.__expo` deprecated in Expo SDK 40.   
The warning showing due to the usage of `global.__expo.Icon` in `icon.service.tsx`.  

Thank you ...

### Steps to reproduce the behavior:
- Init react native project using SDK 40
- add react-native-magnus
- use Icon component 

<img width="1036" alt="Screen Shot 2020-12-15 at 16 36 56" src="https://user-images.githubusercontent.com/7936061/102199044-b5075b80-3ef5-11eb-9d9c-1fc993857027.png">

### Important Details
-

**Comment by jsartisan** [comment]
Thanks for reporting it :) I'll fix it before releasing the new version.

**Comment by jsartisan** [comment]
@rifaldhiaw Fixed in v1.0.57
