### ISSUE TITLE
[Bug] Header height

### ISSUE THREAD

**Issue by erickriva** [jsartisan/react-native-magnus#55]
## Description

Header can't keep same height with and without prefix/suffix without set a fixed height. This can be a problem if you want to hide prefix/suffix and wants to Header to mantain it's height.

### Steps to reproduce the behaviour:

Use Header component with and without prefix/suffix.

![whatsapp-image-2020-12-17-at-1](https://user-images.githubusercontent.com/2746558/102521829-b079a900-4095-11eb-8b27-6f7b7292b444.jpg)

**Comment by jsartisan** [comment]
@erickriva This one is fixed on my end. I used minH in defaultProps with value 70.

**Comment by erickriva** [comment]
> @erickriva This one is fixed on my end. I used minH in defaultProps with value 70.

I was trying to do it in another way, but i think this is the best choice.

**Comment by erickriva** [comment]
Resolved on v1.0.57
