### ISSUE TITLE
Support breakpoints

### ISSUE THREAD

**Issue by nandorojo** [jsartisan/react-native-magnus#6]
A great part of `chakra-ui` and `theme-ui` is that you can use an array of design tokens to give different styles for [different breakpoints](https://chakra-ui.com/responsive-styles).

```jsx
// chakra example

<Box
  height="40px"
  bg="teal.400"
  width={[
    '100%', // base
    '50%', // 480px upwards
    '25%', // 768px upwards
    '15%' // 992px upwards
  ]}
/>
```

If this library supported this kind of styling, it would be the first of its kind for React Native. It would mean using the @expo + next.js integration (or any React Native Web project) could have universal, responsive styles.

I think the solution would be to use [`@expo/match-media`](https://github.com/expo/match-media) to polyfill the browser's matchMedia API, and then and conditionally render styles based on a certain breakpoint, using [`react-responsive`](https://www.npmjs.com/package/react-responsive) to know what the current media query is.

# Example

Here is an example by @EvanBacon using matchMedia and `react-responsive`: https://snack.expo.io/@bacon/4e2f09

...and a great article by Evan explaining it: https://blog.expo.io/media-queries-with-react-native-for-ios-android-and-web-e0b73ed5777b

**Comment by jsartisan** [comment]
@nandorojo Great Suggestion. I'll check on this today.

**Comment by nandorojo** [comment]
Also, it would be great if each token could also be `null`, meaning the style would be ignored for that breakpoint (as is the behavior on `theme-ui`)

**Comment by jsartisan** [comment]
@nandorojo Can you join us on discord channel? Would love to have you there for your great suggestions.

**Comment by jsartisan** [comment]
@nandorojo Started working on the feature on this weekend. Still in progress though but I am loving it while using it

https://github.com/jsartisan/react-native-magnus/tree/feature/responsive-props

**Comment by solarsoft0** [comment]
@jsartisan is there any update on this :)

**Comment by smlarkin** [comment]
@jsartisan Is this feature likely to be implemented soon?  I am considering building a new app on with Mingus (because it is awesome) but I will need React Native Web support -- as in breakpoints for the entire range of devices.  Either way, cheers!

**Comment by jsartisan** [comment]
@smlarkin Yes. This is next on my task list. :D

**Comment by jsartisan** [comment]
@smlarkin But I did start on this feature in the branch `feature/responsive-props`
