### ISSUE TITLE
[Bug] Example App and Components Usage Example Not Working

### ISSUE THREAD

**Issue by JessedeJonge** [jsartisan/react-native-magnus#70]
## Description
- Example App mentioned in [README](https://github.com/jsartisan/react-native-magnus#examples) requires a login and then returns an 403 when opening it in Expo GO.

- Components Usage Example mentioned in [README](https://github.com/jsartisan/react-native-magnus#examples-1) fails due to undefined error.

### Steps to reproduce the behaviour:
Open both examples in Expo Go.
![image](https://user-images.githubusercontent.com/14309234/107019478-00c1dd00-67a2-11eb-9061-27bf5538b457.png)

**Comment by JessedeJonge** [comment]
Might also consider just linking to the website's example page, and leave the examples out of the README.md

**Comment by jsartisan** [comment]
@jsartisan Fixed the snack on expo. Thanks for pointing it out. 

> Might also consider just linking to the website's example page, and leave the examples out of the README.md
Sure. I'll do that.
