### ISSUE TITLE
provide a way to configure default props of the components

### ISSUE THREAD

**Issue by iamhrayr** [jsartisan/react-native-magnus#73]
## Summary

It would be really nice if we can somehow configure the default props of components.

## Motivation
In most cases, developers will not use the out of box styling of the components. Instead, they will pass some props to get the desirable UI result. Providing a default props possibility will really save developers from a lot of repetition.

**Comment by erickriva** [comment]
Hello @iamhrayr !
Actually, it can be done through theme.
But it's recent and docs wasn't updated yet.

In the actual version (1.0.60), you can set it like this:

`const theme = {
     components: {
          Button: {
              bg: "red500",
              color: "red900",
              textTransform: "uppercase"
          },
         Text: {
             color: "black"
         }
     }
}`
and set this theme to ThemeProvider.
If you use Typescript, you can use "ThemeType" on your theme.

In next version (1.0.61, that probably will be launched on Saturday or Sunday), you will be able to also set variants for each component.

You will can use like this:

`const theme = {
     components: {
          Button: {
              bg: "gray500",
              color: "gray900",
              textTransform: "uppercase",

              variants: {
                  danger: {
                      bg: "red500",
                      color: "red900"
                  }
              }
          },
         Text: {
             color: "black"
         }
     }
}`
and use "variant" prop on component like:

`<Button variant="danger">Danger button</Button>`

Props from this variant will be:
default props you set for component + the default props you set for this variant.

**Comment by iamhrayr** [comment]
that's wonderful news! Variants are even more inspiring 👍

**Comment by erickriva** [comment]
Hello @iamhrayr!
Version 1.0.61 launched today with 'variants' support.
Please, feel free to give us your feedback.

**Comment by iamhrayr** [comment]
@erickriva looks really good, thanks. 
I think it's time to close this issue.
