### ISSUE TITLE
[Docs] validate-color missing in peer dependencies information in documentation

### ISSUE THREAD

**Issue by gustperz** [jsartisan/react-native-magnus#74]
## Documentation Link

https://magnus-ui.com/docs/getting-started/

## Describe the problem

In documentation
![image](https://user-images.githubusercontent.com/9136712/107157538-943a1000-6952-11eb-9253-6c7ff1373697.png)

but in your [package,json](https://github.com/jsartisan/react-native-magnus/blob/master/package.json#L73)

```json
"peerDependencies": {
    "color": "^3.1.2",
    "deepmerge": "^4.2.2",
    "react": "*",
    "react-native": "*",
    "react-native-animatable": "^1.3.3",
    "react-native-modal": "^11.5.6",
    "react-native-vector-icons": "^6.6.0",
    "validate-color": "^2.1.1"
  },
```

**Comment by erickriva** [comment]
Hello @gustperz!
Maybe it's a browser cache problem, this info already is in the docs.

![image](https://user-images.githubusercontent.com/2746558/107158218-6dd29f80-6967-11eb-94da-29d27a7f346f.png)

We're looking how to improve dependencies, so maybe some of this packages will be automatically installed on next versions.

**Comment by gustperz** [comment]
> Hello @gustperz!
> Maybe it's a browser cache problem, this info already is in the docs.

You're right, now if i see it correctly
