### ISSUE TITLE
[Feature] Global Snackbar Component

### ISSUE THREAD

**Issue by JessedeJonge** [jsartisan/react-native-magnus#75]
A global component that can be triggered with either React Hooks or with a ref. Just like: https://github.com/arnnis/react-native-fast-toast#global-example

Example Snack: https://snack.expo.io/@jesse_dejonge/1a3b99 (this however uses the same countdown values in multiple instances)

**Comment by erickriva** [comment]
Hello @JessedeJonge!
This is a very interesting idea.
Do you think it needs to allow have only 1 or more snackbars at same time globally?

**Comment by JessedeJonge** [comment]
@erickriva One snackbar would be a good start. The example I gave stacks the toasts by default, which is also nice.

**Comment by erickriva** [comment]
Hello @JessedeJonge!
The implementation is almost ready. It will be available on next version.
I can't confirm right now when it will be launched, but probably next week.

**Comment by JessedeJonge** [comment]
@erickriva Just looked at the feature branch! Looks good. Looking forward to using it. Thanks.
