### ISSUE TITLE
[Enhancement] support "start" and "end" for all props like padding, margin, border, etc...

### ISSUE THREAD

**Issue by iamhrayr** [jsartisan/react-native-magnus#77]
## Summary

Sometimes we use `reversed` flex-direction, so it's better to support props like `padding-start`, `border-end`, and similar props to respect reversed flex direction.

**Comment by erickriva** [comment]
Hello @iamhrayr! You have a good point.

Do you think props like **ps**/**pe** (padding-start/padding-end) should be added to work together, or should replace **pl**/**pr** (padding-left/padding-right)?

**Comment by iamhrayr** [comment]
@erickriva thanks for the quick response.
I think it's better to support both (`pl/pr` and `ps/pe`) to not break the existing codes.

**Comment by erickriva** [comment]
Hello @iamhrayr!
We're working on it and will be available on next version.
I can't confirm right now when it will be launched, but probably next week.

**Comment by iamhrayr** [comment]
@erickriva great, thanks!

**Comment by jsartisan** [comment]
This is done in 1.0.62 :)
