### ISSUE TITLE
Npm versioning seems to be messed up [Bug]

### ISSUE THREAD

**Issue by hixus** [jsartisan/react-native-magnus#84]
## Description

Latest npm package seems to be 1.0.62 which seems to match with repos 1.0.60 tag (also latest release according to repository). This causes confusion about what changes are in which packages.

**Comment by jsartisan** [comment]
@hixus Hey really for this confusion. I'll using some tools to streamline the release process with proper changelog. Tried https://intuit.github.io/auto/docs. Checking out a few more. Do you know any tools for such purposes?

PS: added the release on the repo.

**Comment by bebraw** [comment]
@jsartisan https://www.npmjs.com/package/@changesets/cli is worth a look as it's designed for the purpose. What you do is to write a changeset for each change you make to the source and then the tool will compile the changesets to a release on publish.
