### ISSUE TITLE
[Docs] The Questions and Help link in Issues links to incorrect Discord account

### ISSUE THREAD

**Issue by wadewadewadewadewadewade** [jsartisan/react-native-magnus#88]
## Documentation Link

https://github.com/jsartisan/react-native-magnus/issues

## Describe the problem

If you go to create a "New Issue" here in GitHub, you get taken to https://github.com/jsartisan/react-native-magnus/issues/new/choose. If you click on "Open" next to "Questions and Help" you get taken to a Discord account. One of the members of that Discord account says they doesn't have any relationship to Magnus UI.

## Describe the improvement

Perhaps you could remove the link, or attach that link to a valid Discord account?

**Comment by jsartisan** [comment]
That's embarrassing. Sorry for that. Fixed it already.
